name: Test

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          cache: maven
      - name: Run tests
        run: mvn clean test -B --file pom.xml
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      - name: Update coverage report
        run: CODECOV_TOKEN=bda65746-2227-4bfe-b735-2ead237a2b7c bash <(curl -s https://codecov.io/bash)